#spring.datasource.url=jdbc:mysql://localhost:3306/javabatch
#spring.datasource.username=root

#spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=create

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/fullstack
    username: root
    password: root
  jpa:
    properties:
     hibernate:
      ddl-auto: create
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 4444
  

management:
  endpoints:
    web: 
      exposure:
        include:
        - "*"
        exclude:
 #       - health
 #       - beans
      base-path: /myactuator
 
  endpoint:
    shutdown:
      enabled: true
        
  info:
   build:
    enabled: true       
   git:
    enabled: true
   env:
    enabled: true        
  
    
        
        
        
        
      