#spring.datasource.url=jdbc:mysql://localhost:3306/javabatch
#spring.datasource.username=root

#spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=create
server:
  port: 4444
  
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/javabatch
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true  
       
management:
  endpoints:
    web: 
      exposure:
        include:
        - "*"
        exclude:
 #       - health
 #       - beans
      base-path: /myactuator
 
  endpoint:
    shutdown:
      enabled: true
        
  info:
   build:
    enabled: true       
   git:
    enabled: true
   env:
    enabled: true        
  
#info:
#  created by: Neeraj Nikam
#  modified: 22June22  
#  training: Java_Microservices      
        
#logging:
# level:
#  com:
#     zensar: debug     
        
        
        
        
      